name: recipes_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  get_it: ^7.2.0
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  syncfusion_flutter_datepicker: ^20.1.61
  cupertino_icons: ^1.0.2
  dart_date: ^1.1.1
  sqflite: ^2.0.3+1
  path: ^1.8.1
  flutter_platform_widgets: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat-Thin
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
    - family: Montserrat-Thin-Italic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf